#!/bin/bash
set -e

cp -R photos/ build/photos
cp style.css build/style.css
cp app.js build/app.js
cp index.html build/index.html
cp favicon.ico build/favicon.ico

s3cmd sync --recursive build/ s3://ev-food-blog
echo -e "\t Successfully deployed to S3"
